"use client";

import { Sparkles } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input, Label, Textarea } from "@/components/ui/input";
import { ApiError } from "@/lib/api/client";
import { useNiches, usePosts, useRunPipeline } from "@/lib/api/hooks";
import { formatCurrency, formatRelativeDate } from "@/lib/utils";

const STATUS_FILTERS = [
  { value: "", label: "All" },
  { value: "queued", label: "Queued" },
  { value: "generating", label: "Generating" },
  { value: "ready", label: "Ready" },
  { value: "scheduled", label: "Scheduled" },
  { value: "posted", label: "Posted" },
  { value: "failed", label: "Failed" },
];

export default function PostsPage() {
  const [statusFilter, setStatusFilter] = useState("");
  const posts = usePosts(statusFilter ? { status: statusFilter } : undefined);
  const niches = useNiches();
  const run = useRunPipeline();
  const [showRun, setShowRun] = useState(false);
  const [draft, setDraft] = useState({
    niche_id: 0,
    topic_title: "",
    topic_content: "",
    video_length: "",
  });

  function onRun(e: React.FormEvent) {
    e.preventDefault();
    if (!draft.niche_id) {
      toast.error("Pick a niche");
      return;
    }
    run.mutate(
      {
        niche_id: draft.niche_id,
        topic_id: null,
        manual_topic_title: draft.topic_title || null,
        manual_topic_content: draft.topic_content,
        video_length: draft.video_length || null,
      },
      {
        onSuccess: () => {
          toast.success("Post generated", { description: "Pipeline finished." });
          setShowRun(false);
        },
        onError: (err) =>
          toast.error("Pipeline failed", {
            description: err instanceof ApiError ? err.message : String(err),
          }),
      },
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Posts</h1>
          <p className="mt-1 text-sm text-slate-500">All posts generated by the pipeline.</p>
        </div>
        <Button onClick={() => setShowRun((v) => !v)}>
          <Sparkles className="h-4 w-4" />
          {showRun ? "Cancel" : "Generate post"}
        </Button>
      </div>

      {showRun && (
        <Card>
          <CardHeader>
            <CardTitle>Run pipeline</CardTitle>
            <CardDescription>
              Synchronous — the request takes 30-90s. Stay on this page while it runs.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={onRun} className="space-y-4">
              <div className="space-y-2">
                <Label>Niche</Label>
                <select
                  value={draft.niche_id}
                  onChange={(e) => setDraft({ ...draft, niche_id: Number(e.target.value) })}
                  className="flex h-10 w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-300"
                  required
                >
                  <option value={0}>Select a niche…</option>
                  {niches.data?.items.map((n) => (
                    <option key={n.id} value={n.id}>
                      {n.name}
                    </option>
                  ))}
                </select>
              </div>
              <div className="space-y-2">
                <Label>Topic title</Label>
                <Input
                  placeholder="e.g. The 5-minute desk routine that fixes your posture"
                  value={draft.topic_title}
                  onChange={(e) => setDraft({ ...draft, topic_title: e.target.value })}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label>Topic context (optional)</Label>
                <Textarea
                  rows={3}
                  value={draft.topic_content}
                  onChange={(e) => setDraft({ ...draft, topic_content: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label>Video length</Label>
                <select
                  value={draft.video_length}
                  onChange={(e) => setDraft({ ...draft, video_length: e.target.value })}
                  className="flex h-10 w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-300"
                >
                  <option value="">Niche default</option>
                  <option value="short">Short (vertical 9:16)</option>
                  <option value="long">Long (horizontal 16:9)</option>
                </select>
              </div>
              <Button type="submit" disabled={run.isPending}>
                {run.isPending ? "Generating… (30-90s)" : "Generate"}
              </Button>
            </form>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader className="flex flex-row items-center justify-between gap-2 space-y-0">
          <CardTitle>All posts</CardTitle>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="h-9 rounded-md border border-slate-200 bg-white px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-300"
          >
            {STATUS_FILTERS.map((f) => (
              <option key={f.value} value={f.value}>
                {f.label}
              </option>
            ))}
          </select>
        </CardHeader>
        <CardContent>
          {posts.isLoading ? (
            <p className="text-sm text-slate-500">Loading…</p>
          ) : posts.data && posts.data.items.length > 0 ? (
            <ul className="divide-y divide-slate-100">
              {posts.data.items.map((p) => (
                <li key={p.id} className="flex items-center justify-between gap-4 py-3">
                  <div className="min-w-0 flex-1">
                    <Link href={`/posts/${p.id}`} className="block text-sm font-medium text-slate-900 hover:underline">
                      {p.caption?.split("\n")[0]?.slice(0, 100) || `Post #${p.id}`}
                    </Link>
                    <p className="mt-0.5 text-xs text-slate-500">
                      {p.status} · {p.video_length} · {p.image_count} images ·{" "}
                      {formatRelativeDate(p.generated_at ?? p.created_at)}
                    </p>
                  </div>
                  <span className="text-xs text-slate-400">{formatCurrency(p.media_cost_usd ?? 0)}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="py-6 text-center text-sm text-slate-500">
              No posts yet. Click &quot;Generate post&quot; above to create your first one.
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
