"""posting_attempt_post_id_and_nullable_schedule

Revision ID: 8827eb41cb68
Revises: 39c6e5aae1ea
Create Date: 2026-05-19 20:29:03.397148

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8827eb41cb68'
down_revision: Union[str, None] = '39c6e5aae1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.alter_column('schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_posting_attempts_post_id'), ['post_id'], unique=False)
        batch_op.create_foreign_key('fk_posting_attempts_post_id', 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posting_attempts_post_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_posting_attempts_post_id'))
        batch_op.alter_column('schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
