"""swap_stripe_columns_for_whop

Revision ID: f038ded5c50d
Revises: b636ee2e7427
Create Date: 2026-05-20 00:17:28.039697

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f038ded5c50d'
down_revision: Union[str, None] = 'b636ee2e7427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whop_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('whop_membership_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('whop_product_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('whop_status_raw', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('whop_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_tenants_whop_membership_id'), ['whop_membership_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_whop_user_id'), ['whop_user_id'], unique=False)
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_tenants_whop_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_whop_membership_id'))
        batch_op.drop_column('whop_expires_at')
        batch_op.drop_column('whop_status_raw')
        batch_op.drop_column('whop_product_id')
        batch_op.drop_column('whop_membership_id')
        batch_op.drop_column('whop_user_id')

    # ### end Alembic commands ###
