"use client";

import Link from "next/link";
import { Calendar, FileText, Play, Sparkles, Wallet } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useMe, useNiches, usePosts, useRunAutomation, useSchedules, useUsageSummary } from "@/lib/api/hooks";
import { formatCurrency, formatRelativeDate } from "@/lib/utils";

export default function DashboardPage() {
  const me = useMe();
  const niches = useNiches();
  const posts = usePosts();
  const scheduled = useSchedules({ status: "pending" });
  const usage = useUsageSummary();
  const runAutomation = useRunAutomation();

  const totalPosts = posts.data?.meta.total ?? 0;
  const queuedCount = scheduled.data?.meta.total ?? 0;
  const monthCost = usage.data?.total_cost_usd ?? 0;
  const monthLabel = usage.data?.month ?? "—";

  function onRunNow() {
    toast.info("Running automation… this can take a minute while videos generate.");
    runAutomation.mutate(undefined, {
      onSuccess: (d) => toast.success(d.message, { duration: 12_000 }),
      onError: (err) => toast.error(err instanceof Error ? err.message : "Automation failed", { duration: 12_000 }),
    });
  }

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">Dashboard</h1>
          <p className="mt-1 text-sm text-slate-500">
            {me.data ? `Workspace: ${me.data.tenant_name}` : "Loading…"}
          </p>
        </div>
        <Button onClick={onRunNow} disabled={runAutomation.isPending}>
          <Play className="h-4 w-4" />
          {runAutomation.isPending ? "Running…" : "Run automation now"}
        </Button>
      </div>

      <Card className="border-blue-100 bg-blue-50/50">
        <CardContent className="py-4">
          <p className="text-sm text-slate-700">
            <span className="font-semibold">How autonomous posting works:</span> the worker discovers
            topics from your Topic Sources every 30 min, generates up to your daily limit of short/long
            videos every 15 min, and posts scheduled videos every minute. Set your daily limits in{" "}
            <Link href="/settings" className="font-medium text-blue-600 hover:underline">Settings</Link>.
            Use <span className="font-medium">Run automation now</span> to trigger one full cycle immediately.
          </p>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Tile
          label="Posts generated"
          value={totalPosts}
          icon={<FileText className="h-5 w-5" />}
          href="/posts"
        />
        <Tile
          label="Scheduled"
          value={queuedCount}
          icon={<Calendar className="h-5 w-5" />}
          href="/schedule"
        />
        <Tile
          label={`Spend (${monthLabel})`}
          value={formatCurrency(monthCost)}
          icon={<Wallet className="h-5 w-5" />}
          href="/usage"
        />
        <Tile
          label="Niches"
          value={niches.data?.meta.total ?? 0}
          icon={<Sparkles className="h-5 w-5" />}
          href="/niches"
        />
      </div>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between gap-2 space-y-0">
          <div>
            <CardTitle>Recent posts</CardTitle>
            <CardDescription>The last 5 posts generated by the pipeline.</CardDescription>
          </div>
          <Link href="/posts">
            <Button variant="outline">View all</Button>
          </Link>
        </CardHeader>
        <CardContent>
          {posts.isLoading ? (
            <p className="text-sm text-slate-500">Loading…</p>
          ) : posts.data && posts.data.items.length > 0 ? (
            <ul className="divide-y divide-slate-100">
              {posts.data.items.slice(0, 5).map((p) => (
                <li key={p.id} className="flex items-center justify-between py-3">
                  <div className="min-w-0 flex-1">
                    <Link
                      href={`/posts/${p.id}`}
                      className="block truncate text-sm font-medium text-slate-900 hover:underline"
                    >
                      {p.caption?.split("\n")[0]?.slice(0, 90) || `Post #${p.id}`}
                    </Link>
                    <p className="mt-0.5 text-xs text-slate-500">
                      {p.status} · {p.video_length} · {formatRelativeDate(p.generated_at ?? p.created_at)}
                    </p>
                  </div>
                  <span className="ml-4 text-xs text-slate-500">
                    {formatCurrency(p.media_cost_usd ?? 0)}
                  </span>
                </li>
              ))}
            </ul>
          ) : (
            <EmptyState
              title="No posts yet"
              cta={
                <Link href="/niches">
                  <Button>Set up your first niche</Button>
                </Link>
              }
            />
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function Tile({
  label,
  value,
  icon,
  href,
}: {
  label: string;
  value: string | number;
  icon: React.ReactNode;
  href: string;
}) {
  return (
    <Link
      href={href}
      className="block rounded-lg border border-slate-200 bg-white p-4 shadow-sm transition-all hover:border-slate-300 hover:shadow-md"
    >
      <div className="flex items-center justify-between">
        <p className="text-sm font-medium text-slate-500">{label}</p>
        <span className="text-slate-400">{icon}</span>
      </div>
      <p className="mt-2 text-2xl font-bold tracking-tight text-slate-900">{value}</p>
    </Link>
  );
}

function EmptyState({ title, cta }: { title: string; cta?: React.ReactNode }) {
  return (
    <div className="flex flex-col items-center justify-center gap-3 rounded-md border border-dashed border-slate-200 bg-slate-50 py-10 text-center">
      <p className="text-sm text-slate-500">{title}</p>
      {cta}
    </div>
  );
}
